---
- name: Modify bookkeeper config file - {{ bk_conf_file }}
  lineinfile:
    path: "{{ bk_conf_file }}"
    regexp: '^zkServers='
    line: "zkServers={{ zk_list_str }}"

- name: Check if bookkeeper server is already running
  stat:
    path: "{{ tgt_pulsar_inst_dir }}/bin/pulsar-bookie.pid"
  register: stat_result

- name: Start bookeeper server, if it is not running yet
  become: true
  become_method: sudo
  become_user: "{{ pulsar_user }}"
  shell: "{{ tgt_pulsar_inst_dir }}/bin/pulsar-daemon start bookie"
  when: not stat_result.stat.exists

- name: Verifiy whether bookie works properly by running "bin/bookkeeper shell bookiesanity" command
  shell: "{{ tgt_pulsar_inst_dir }}/bin/bookkeeper shell bookiesanity > bookie_sanity_check.result"
  register: bookie_shell_output
  #failed_when:
    #- bookie_shell_output.rc != 0
    #- not bookie_shell_output.stdout is search('Bookie sanity test succeeded')
#- debug: msg="{{ bookie_shell_output }}"

  