---
- name: Modify Pulsar client configuration file - {{ pulsar_client_config_file }}
  lineinfile:
    path: "{{ pulsar_client_config_file }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^webServiceUrl=', line: 'webServiceUrl=http://{{ web_service_url_str }}' }
    - { regexp: '^brokerServiceUrl=', line: 'brokerServiceUrl=pulsar://{{ broker_service_url_str }}' }