---
- name: Check if bookkeeper server is already running
  stat:
    path: "{{ tgt_pulsar_inst_dir }}/bin/pulsar-bookie.pid"
  register: stat_result

- name: Start bookeeper server, if it is not running yet
  become: true
  become_method: sudo
  become_user: "{{ pulsar_user }}"
  shell: "{{ tgt_pulsar_inst_dir }}/bin/pulsar-daemon start bookie"
  when: not stat_result.stat.exists

- name: Wait until bookkeeper listeneing port {{ bookie_listening_port }} is ready
  wait_for:
    host: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    port: "{{ bookie_listening_port }}"
    delay: 2
    timeout: 120