---
- hosts: zookeeper
  gather_facts: true
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles: 
    - { role: inst_pulsar_bin }
    - { role: get_proper_url_list, run_once: true }
    - { role: deploy_zookeeper, when: not standalone_zk | bool }
    - { role: init_cluster_metadata, run_once: true }


- hosts: bookkeeper
  gather_facts: true
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles: 
    - { role: inst_pulsar_bin, when: not share_zk | bool }
    - { role: get_proper_url_list, run_once: true }
    - { role: deploy_bookkeeper, when: not standalone_bk | bool }

- hosts: pulsar_broker
  gather_facts: true
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles: 
    - { role: inst_pulsar_bin, when: not share_zk | bool }
    - { role: get_proper_url_list, run_once: true }
    - { role: deploy_pulsar_broker }
    - { role: test_pulsar_client }
