---
- name: Add a system user "{{ pulsar_user }}"
  user: 
    name: "{{ pulsar_user }}"
    create_home: false
    system: yes
    state: present

- name: Create folder "{{ tgt_pkg_dir }}" 
  file:
    path: "{{ tgt_pkg_dir }}"
    state: directory
    recurse: yes
    owner: "{{ pulsar_user }}"
    group: "{{ pulsar_user }}"

- name: Download pulsar version "{{ pulsar_ver }}"
  get_url:
    url: "{{ pulsar_bin_download_url }}"
    dest: "{{ tgt_pkg_dir }}/apache-pulsar-{{ pulsar_ver }}-bin.tar.gz"
    owner: "{{ pulsar_user }}"
    group: "{{ pulsar_user }}"

- name: Create folder "{{ tgt_pulsar_inst_dir }}"
  file:
    path: "{{ tgt_pulsar_inst_dir }}"
    state: directory
    owner: "{{ pulsar_user }}"
    group: "{{ pulsar_user }}"

- name: Extract downloaded Pulsar binary archive file to folder "{{ tgt_pulsar_inst_dir }}"
  unarchive:
    src: "{{ tgt_pkg_dir }}/apache-pulsar-{{ pulsar_ver }}-bin.tar.gz"
    remote_src: yes
    dest: "{{ tgt_pulsar_inst_dir }}"
    extra_opts: [--strip-components=1]
    owner: "{{ pulsar_user }}"
    group: "{{ pulsar_user }}"

- name: Create folder "{{ tgt_pulsar_inst_dir }}/connectors", if needed 
  file:
    path: "{{ tgt_pulsar_inst_dir }}/connectors"
    state: directory
    owner: "{{ pulsar_user }}"
    group: "{{ pulsar_user }}"
    recurse: yes
  when: builtin_connector|bool

- name: Download Pulsar built-in I/O Connectors, if needed
  get_url:
    url: "{{ pulsar_connector_download_url_base }}/pulsar-io-{{ item }}-{{ pulsar_ver }}.nar"
    dest: "{{ tgt_pulsar_inst_dir }}/connectors/pulsar-io-{{ item }}-{{ pulsar_ver }}.nar"
    owner: "{{ pulsar_user }}"
    group: "{{ pulsar_user }}"
  with_items:
    - "{{ pulsar_connectors }}"
  when: builtin_connector|bool

- name: Create folder "{{ tgt_pulsar_inst_dir }}/offloaders", if needed 
  file:
    path: "{{ tgt_pulsar_inst_dir }}/offloaders"
    state: directory
    owner: "{{ pulsar_user }}"    
    group: "{{ pulsar_user }}"    
    recurse: yes
  when: builtin_connector | bool

- name: Download Pulsar TieredStorage Offloaders, if needed
  get_url:
    url: "{{ pulsar_ts_offloader_bin_download_url }}"
    dest: "{{ tgt_pkg_dir }}/apache-pulsar-offloaders-{{ pulsar_ver }}-bin.tar.gz"
    owner: "{{ pulsar_user }}"
    group: "{{ pulsar_user }}"
  when: tierstorage_offloader | bool

- name: Extract downloaded Pulsar TieredStorage Offloader archive file to folder "{{ tgt_pulsar_inst_dir }}/offloaders"
  unarchive:
    src: "{{ tgt_pkg_dir }}/apache-pulsar-offloaders-{{ pulsar_ver }}-bin.tar.gz"
    remote_src: yes
    dest: "{{ tgt_pulsar_inst_dir }}/offloaders"
    extra_opts: [--strip-components=2]
    owner: "{{ pulsar_user }}"    
    group: "{{ pulsar_user }}"

- name: Fix permissions on the extract directory and sub-directories
  file:
    path: "{{ tgt_pulsar_inst_dir }}"
    owner: "{{ pulsar_user }}"    
    group: "{{ pulsar_user }}"
    recurse: yes

- name: Change Pulsar log folder permission
  file:
    path: "{{ tgt_pulsar_inst_dir }}/logs/"
    state: directory
    mode: 0775
    owner: "{{ pulsar_user }}"    
    group: "{{ pulsar_user }}"  