- name: Launch prometheus and grafana containers using docker-compose
  docker_compose:
    project_src: "{{ tgt_metrics_compose_homedir }}/prometheus/"
    state: present
  register: dc_output
# - debug:     
#     var: dc_output