---
- name: Modify bookkeeper config file - {{ bk_conf_file }}
  lineinfile:
    path: "{{ bk_conf_file }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^bookiePort=', line: 'bookiePort={{ bookie_listening_port }}' }
    - { regexp: '^zkServers=', line: 'zkServers={{ zk_list_str }}' }
    - { regexp: '^httpServerPort=', line: 'httpServerPort={{ bk_stats_port }}' }
    - { regexp: '^prometheusStatsHttpPort=', line: 'prometheusStatsHttpPort={{ bk_stats_port }}' }