--- 
- name: Copy prometheus and grafana docker-compose.yaml file to remote
  file: 
    path: "{{ tgt_metrics_compose_homedir }}"
    state: directory
    mode: 0755

- name: Upload docker-compose files
  copy: 
    src: "../docker/prom_grafana/"
    dest: "{{ tgt_metrics_compose_homedir }}"

- name: Replace template string for Pulsar cluster name in "prometheus.yaml" file
  replace:
    path: "{{ tgt_metrics_compose_homedir }}/prometheus/{{ item }}"
    regexp: "{{ pulsar_cluster_name_template_tag }}"
    replace: "{{ pulsar_cluster_name }}"
  with_items:
    - "tg_pulsar_zookeeper.json"
    - "tg_pulsar_bookkeeper.json"
    - "tg_pulsar_broker.json"


- template: src={{ item }}_metrics_list.j2 dest=/tmp/{{ item }}_scrape_list mode=0664
  with_items:
    - broker
    - bookie
    - zookeeper

- name: Replace template string in scrape target node list file for Graphite
  replace:
    path: "{{ tgt_metrics_compose_homedir }}/prometheus/tg_graphite.json"
    regexp: "{{ graphite_scape_target_template_tag }}"
    #replace: "{{ inventory_hostname }}"
    replace: "\"{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ graphite_exporter_scrape_port }}\""

- shell: cat /tmp/broker_scrape_list
  register: "broker_scrape_list_cmdcat"
- name: Replace template string in scrape target node list file for Pulsar brokers
  replace:
    path: "{{ tgt_metrics_compose_homedir }}/prometheus/tg_pulsar_broker.json"
    regexp: "{{ pulsar_broker_scape_target_template_tag }}"
    replace: "{{ broker_scrape_list_cmdcat.stdout | to_json | regex_replace(', ', '\", \"') }}"

- shell: cat /tmp/bookie_scrape_list
  register: "bookie_scrape_list_cmdcat"
- name: Replace template string in scrape target node list file for Pulsar bookies
  replace:
    path: "{{ tgt_metrics_compose_homedir }}/prometheus/tg_pulsar_bookkeeper.json"
    regexp: "{{ pulsar_bookie_scape_target_template_tag }}"
    replace: "{{ bookie_scrape_list_cmdcat.stdout | to_json | regex_replace(', ', '\", \"') }}"

- shell: cat /tmp/zookeeper_scrape_list
  register: "zookeeper_scrape_list_cmdcat"    
- name: Replace template string in scrape target node list file for Pulsar zookeepers
  replace:
    path: "{{ tgt_metrics_compose_homedir }}/prometheus/tg_pulsar_zookeeper.json"
    regexp: "{{ pulsar_zookeeper_scape_target_template_tag }}"
    replace: "{{ zookeeper_scrape_list_cmdcat.stdout | to_json | regex_replace(', ', '\", \"') }}"