---
# Download Pulsar binaries
- hosts: pulsar_clnt
  gather_facts: true
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles: 
    ## OS distro
    - { role: inst_pulsar_bin, when: inst_pulsar_bin is not defined or inst_pulsar_bin|bool}
    ## DS distro
    #- { role: inst_pulsar_ds_distro_bin, when: inst_pulsar_bin is not defined or inst_pulsar_bin|bool}



# Make necessary configuration changes for all Pulsar components
- hosts: pulsar_cluster_core
  gather_facts: false
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles: 
    # Get required node:port strings that are needed in various configuration files
    - { role: pulsar_common, run_once: true }
    # Config and start zookeepers  
    - { role: config_zookeeper, when: not standalone_zk|bool and zookeeper|bool }
    # Config and start bookies
    - { role: config_bookkeeper, when: not standalone_bk|bool and bookie|bool }
    # Config and start brokers
    - { role: config_pulsar_broker, when: broker|bool }


# Start Zookeeper nodes first, one by one
- hosts: pulsar_cluster_core
  gather_facts: false
  any_errors_fatal: true
  become: true
  become_method: sudo
  serial: 1
  roles: 
    - { role: start_svc_zookeeper, when: not standalone_zk|bool and zookeeper|bool }


# Initialzie cluster metadata after Zookeeper is up
- hosts: pulsar_cluster_core
  gather_facts: false
  any_errors_fatal: true
  become: true
  become_method: sudo
  run_once: true
  roles: 
    - { role: init_cluster_metadata, run_once: true }


# Start Bookkeeper nodes, one by one
- hosts: pulsar_cluster_core
  gather_facts: false
  any_errors_fatal: true
  become: true
  become_method: sudo
  serial: 1
  roles: 
    - { role: start_svc_bookie, when: not standalone_bk|bool and bookie|bool }
  tasks:
    # Test whether bookie functions properly after they're up and running
    - name: Verifiy whether bookie works properly by running "bin/bookkeeper shell bookiesanity" command
      become: false
      shell: "{{ tgt_pulsar_inst_dir }}/bin/bookkeeper shell bookiesanity > bookie_sanity_check.result"
      register: bookie_shell_output
      when: not standalone_bk|bool and bookie|bool
    - debug: msg="{{ bookie_shell_output }}"
      when: show_debug_msg|bool


# Start Pulsar broker nodes, one by one
- hosts: pulsar_cluster_core
  gather_facts: false
  any_errors_fatal: true
  become: true
  become_method: sudo
  serial: 1
  roles: 
    - { role: start_svc_broker, when: broker|bool }


# Configure Pulsar client
- hosts: pulsar_clnt
  gather_facts: true
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles: 
    - { role: pulsar_common, run_once: true }
    - { role: config_pulsar_client }