- hosts: pulsar_perf
  gather_facts: false
  any_errors_fatal: true
  vars:
    python_verion: 3.9.0
  roles:
    - { role: python3_inst }
  tasks:
    - name: Create a folder to host Pulsar perf benchmark script
      file:
        path: "/home/{{ ansible_ssh_user }}/ppfb"
        state: directory
        recurse: yes
        mode: '0755'
        owner: "{{ ansible_ssh_user }}"
        group: "{{ ansible_ssh_user }}"
  
    - name: Download Pulsar perf benchmark script
      get_url:
        url: "https://raw.githubusercontent.com/yabinmeng/pulsar_perf_bench/master/{{ item }}"
        dest: /home/{{ ansible_ssh_user }}/ppfb
        mode: '0666'
        owner: "{{ ansible_ssh_user }}"
        group: "{{ ansible_ssh_user }}"
      with_items:
        - "pperf_bench.py"
        - "ppfb.yaml"

    - name: Install "screen" command 
      become: true
      become_method: sudo
      apt:
        name: screen
        update_cache: true