---
- hosts: pulsar_manager
  gather_facts: false
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles:
    - { role: stop_svc_pulsar_mgr }

- hosts: pulsar_metrics
  gather_facts: false
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles:
    - { role: stop_svc_prom_graf }
  tasks:
  - name: Delete pulsar metrics docker compose folder if requested
    file:
      path: "{{ tgt_metrics_compose_homedir }}"
      state: absent
    when:
      del_inst is defined and del_inst|bool