---
- hosts: pulsar_cluster_core
  gather_facts: false
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles:
    - { role: stop_svc_broker, when: broker|bool }
    - { role: stop_svc_bookie, when: bookie|bool }
    - { role: stop_svc_zookeeper, when: zookeeper|bool }


- hosts: pulsar_cluster_external
  gather_facts: false
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles:
    - { role: stop_svc_pulsar_mgr, when: pulsar_manager|bool }
    - { role: stop_svc_prom_graf, when: metrics_monitor|bool }


- hosts: pulsar_clnt
  gather_facts: false
  any_errors_fatal: true
  become: true
  become_method: sudo
  tasks:
  - name: Delete installation directory if requested
    file:
      path: "{{ tgt_pulsar_inst_dir }}"
      state: absent
    when:
      del_inst is defined and del_inst|bool


- hosts: pulsar_cluster_external
  gather_facts: false
  any_errors_fatal: true
  become: true
  become_method: sudo
  tasks:
  - name: Delete pulsar metrics docker compose folder if requested
    file:
      path: "{{ tgt_metrics_compose_homedir }}"
      state: absent
    when:
      metrics_monitor|bool and del_inst is defined and del_inst|bool