- name: Check if docker-compose.yaml file exists
  stat:
    path: "{{ tgt_metrics_compose_homedir }}/prometheus/docker-compose.yaml"
  register: dc_file

- name: Stop prometheus and grafana containers using docker-compose
  docker_compose:
    project_src: "{{ tgt_metrics_compose_homedir }}/prometheus/"
    state: absent
  when: dc_file.stat.exists