---
- name: Check if bookkeeper server is already running
  stat:
    path: "{{ tgt_pulsar_inst_dir }}/bin/pulsar-bookie.pid"
  register: stat_result
  
- name: Stop bookkeeper server if it is running
  shell: "{{ tgt_pulsar_inst_dir }}/bin/pulsar-daemon stop bookie"
  when: stat_result.stat.exists